# Generated by Django 2.2.13 on 2020-07-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0049_layer_download_gpx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleProDTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('dtm_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='EleProProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleprofile_projects', to='qdjango.Project')),
            ],
        ),
        migrations.CreateModel(
            name='EleProLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elepro_dtm_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_layers', to='eleprofile.EleProDTM')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Layer')),
            ],
        ),
        migrations.AddField(
            model_name='eleprodtm',
            name='elepro_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_layers', to='eleprofile.EleProProject'),
        ),
    ]
