# Generated by Django 2.2.13 on 2020-07-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleprodtm',
            options={'verbose_name': 'Elevation Profile DTM Layers'},
        ),
        migrations.AlterModelOptions(
            name='eleprolayer',
            options={'verbose_name': 'Elevation Profile Line Layers'},
        ),
        migrations.AlterModelOptions(
            name='eleproproject',
            options={'verbose_name': 'Elevation Profile Projects'},
        ),
    ]
