# Generated by Django 2.2.13 on 2020-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleprofile', '0004_auto_20200713_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleprodtm',
            name='dtm_delta',
            field=models.ImageField(default=10, upload_to='', verbose_name='Sampling DTM step, default 10 (map units)'),
        ),
    ]
