# Generated by Django 2.2.13 on 2020-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleprofile', '0005_eleprodtm_dtm_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleprodtm',
            name='dtm_delta',
            field=models.IntegerField(default=10, verbose_name='Sampling DTM step, default 10 (map units)'),
        ),
    ]
