# Generated by Django 2.2.13 on 2020-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleprofile', '0006_auto_20200715_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleprodtm',
            name='dtm_delta',
            field=models.IntegerField(default=10, help_text='Sampling step in map units, default 10', verbose_name='Sampling DTM step'),
        ),
    ]
