# Generated by Django 2.2.13 on 2020-07-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleprofile', '0007_auto_20200715_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleprodtm',
            name='dtm_layer',
            field=models.ForeignKey(help_text='Select DTM project layer to use for sampling', on_delete=django.db.models.deletion.CASCADE, related_name='dtm_layer', to='qdjango.Layer'),
        ),
        migrations.AlterField(
            model_name='eleprodtm',
            name='layers',
            field=models.ManyToManyField(help_text='Select one or more path layers', related_name='path_layer', to='qdjango.Layer'),
        ),
    ]
